### ISSUE TITLE
Pages stopped displaying in browser with Rails 4.2 + rails-dev-tweaks 1.1

### ISSUE THREAD

**Issue by davidcpell** [wavii/rails-dev-tweaks#22]
I am in the process of upgrading our app to Rails 4.2 from 3.2. After getting gem dependencies taken care of, I started the server and began trying to open various static pages. I noticed that, even with a 200 Completed message in the server console, the pages were not loading the browser. The screen just remained white and the "activity" indicator in the tab would spin endlessly. There were no errors in the JS console.

Sometimes this process in the browser never ended, sometimes the page finally loaded but was missing certain assets, other times it finally displayed but still just took a really long time.

After trying a lot of configuration changes in `development.rb` and `application.rb` I decided to just start commenting gems out of the Gemfile. I started with the `development` group since it seemed like the most likely place. Upon completely commenting out that group, the problem went away. So I chose "rails-dev-tweaks" by itself since it seemed like something that might touch asset loading, etc, and when I uncommented that one the problem immediately reoccurred. 

Sorry that my technical skill isn't good enough to comment more on this. It just seems like I have this problem only when the gem is active. Any suggestions?

Rails 4.2
rails-dev-tweaks 1.1.0

**Comment by mahemoff** [comment]
I don't think this project is active anymore. Better to remove it from Gemfile.

https://stackoverflow.com/questions/27992494/rails-4-2-after-upgrade-pages-never-load-in-browser-or-take-really-long-des
"The problem was being caused by a gem called "rails-dev-tweaks" that is no longer needed in Rails 4. Removing that gem fixed the problem."

**Comment by davidcpell** [comment]
Yeah, that's my SO question actually. Forgot to close this issue. Thanks for the reminder!

**Comment by mahemoff** [comment]
:laughing:
:thumbsup:
