### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by karlfreeman** [wavii/rails-dev-tweaks#4]
Would it be possible to allow logging to be configured on / off for https://github.com/wavii/rails-dev-tweaks/blob/master/lib/rails_dev_tweaks/granular_autoload/middleware.rb#L31.

Trying to keep a tidy log ;-)

**Comment by nevir** [comment]
Good call!  Update to 0.5.1 and you should be set with:

```
config.dev_tweaks.log_autoload_notice = false
```
