### ISSUE TITLE
Compatible with Rails ~> 3.2.x

### ISSUE THREAD

**Issue by dinesh** [wavii/rails-dev-tweaks#6]
can we make this compatible with rails latest ~> 3.2.x ?

**Comment by nevir** [comment]
I've just pushed [v0.6.0.preview.1](http://rubygems.org/gems/rails-dev-tweaks/versions/0.6.0.preview.1) with untested support for rails 3.2.x.  Let us know if you run into any issues!

**Comment by mjtko** [comment]
Please see my pull request #7 for a fix required to make rails-dev-tweaks work happily with the new Journey router under rails 3.2.0.

**Comment by nevir** [comment]
Fixed in `v0.6.0`

**Comment by peternash** [comment]
Just tried 0.6.0 and got the following exception:

```
undefined method `app' for #<Array:0xbb913b4>

rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/granular_autoload/matchers/asset_matcher.rb:18:in `journey_find_app'
journey (1.0.1) lib/journey/router.rb:90:in `recognize'
journey (1.0.1) lib/journey/router.rb:84:in `each'
journey (1.0.1) lib/journey/router.rb:84:in `recognize'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/granular_autoload/matchers/asset_matcher.rb:17:in `journey_find_app'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/granular_autoload/matchers/asset_matcher.rb:7:in `call'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/configuration.rb:78:in `should_reload?'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/configuration.rb:77:in `each'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/configuration.rb:77:in `should_reload?'
rails-dev-tweaks (0.6.0) lib/rails_dev_tweaks/granular_autoload/middleware.rb:21:in `call'
```

**Comment by nevir** [comment]
@peternash Can you post up your `Gemfile`?

**Comment by nevir** [comment]
Oh!  @peternash  are you running on Ruby 1.8.x?

**Comment by nevir** [comment]
See if v0.6.1 of the gem does it for you

**Comment by peternash** [comment]
@nevir Yes, should have mentioned it was Ruby 1.8.7 - didn't think to try on 1.9.3.  Your latest v0.6.1 looks OK on both thanks.

**Comment by nevir** [comment]
Awesome!
